/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.TaiKhoanDAO;
import Entity.TaiKhoan;
import Utils.Auth;

/**
 *
 * @author vietm
 */
public class DangNhap_Dialog extends javax.swing.JDialog {

    /**
     * Creates new form DangNhappppppp_Dialog
     */
    public DangNhap_Dialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLog = new javax.swing.JPanel();
        pnlLogin = new javax.swing.JPanel();
        lblText = new javax.swing.JLabel();
        lblText1 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        spr1 = new javax.swing.JSeparator();
        txtPwd = new javax.swing.JPasswordField();
        spr2 = new javax.swing.JSeparator();
        btnLogin = new javax.swing.JButton();
        lblErrorUser = new javax.swing.JLabel();
        lblErrorPwd = new javax.swing.JLabel();
        lblText3 = new javax.swing.JLabel();
        lblErrorImgpwd = new javax.swing.JLabel();
        lblErrorImguser = new javax.swing.JLabel();
        pnlImage = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        pnlLoader = new javax.swing.JPanel();
        lblImgLoad = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TNBank - Login");
        getContentPane().setLayout(new java.awt.CardLayout());

        pnlLog.setBackground(new java.awt.Color(255, 255, 255));
        pnlLog.setLayout(new java.awt.BorderLayout());

        pnlLogin.setBackground(new java.awt.Color(255, 255, 255));

        lblText.setBackground(new java.awt.Color(255, 255, 255));
        lblText.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblText.setForeground(new java.awt.Color(71, 75, 96));
        lblText.setText("Welcome Back TNBank");

        lblText1.setBackground(new java.awt.Color(255, 255, 255));
        lblText1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblText1.setForeground(new java.awt.Color(71, 75, 96));
        lblText1.setText("Hi User");

        txtUser.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtUser.setForeground(new java.awt.Color(71, 75, 96));
        txtUser.setText("Username");
        txtUser.setBorder(null);
        txtUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserFocusGained(evt);
            }
        });

        spr1.setBackground(new java.awt.Color(71, 75, 96));
        spr1.setForeground(new java.awt.Color(71, 75, 96));

        txtPwd.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtPwd.setForeground(new java.awt.Color(71, 75, 96));
        txtPwd.setText("Password");
        txtPwd.setBorder(null);
        txtPwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPwdFocusGained(evt);
            }
        });

        spr2.setBackground(new java.awt.Color(71, 75, 96));
        spr2.setForeground(new java.awt.Color(71, 75, 96));

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(71, 75, 96));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblErrorUser.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblErrorUser.setForeground(new java.awt.Color(255, 51, 51));

        lblErrorPwd.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblErrorPwd.setForeground(new java.awt.Color(255, 51, 51));

        lblText3.setForeground(new java.awt.Color(71, 75, 96));
        lblText3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblText3.setText("Don't have an account yet? Contact Admin");

        lblErrorImgpwd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Error.png"))); // NOI18N

        lblErrorImguser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Error.png"))); // NOI18N

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblText, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                            .addComponent(lblText1)
                            .addComponent(spr1)
                            .addComponent(spr2)
                            .addComponent(lblErrorUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblErrorPwd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblText3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                                .addComponent(txtPwd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblErrorImgpwd))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                                .addComponent(txtUser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblErrorImguser)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblText1)
                .addGap(20, 20, 20)
                .addComponent(lblErrorUser, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spr1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblErrorPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlLoginLayout.createSequentialGroup()
                                .addComponent(txtPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spr2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblText3))
                            .addComponent(lblErrorImgpwd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblErrorImguser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pnlLog.add(pnlLogin, java.awt.BorderLayout.WEST);

        pnlImage.setBackground(new java.awt.Color(255, 255, 255));
        pnlImage.setPreferredSize(new java.awt.Dimension(300, 400));

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/netbanking.png"))); // NOI18N
        lblImage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlImageLayout = new javax.swing.GroupLayout(pnlImage);
        pnlImage.setLayout(pnlImageLayout);
        pnlImageLayout.setHorizontalGroup(
            pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlImageLayout.setVerticalGroup(
            pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlLog.add(pnlImage, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlLog, "card2");

        pnlLoader.setBackground(new java.awt.Color(255, 255, 255));

        lblImgLoad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/loadingTNBank.gif"))); // NOI18N

        lblLogin.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(71, 75, 96));
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin.setText("Login to TNBank...");

        javax.swing.GroupLayout pnlLoaderLayout = new javax.swing.GroupLayout(pnlLoader);
        pnlLoader.setLayout(pnlLoaderLayout);
        pnlLoaderLayout.setHorizontalGroup(
            pnlLoaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImgLoad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addComponent(lblLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlLoaderLayout.setVerticalGroup(
            pnlLoaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoaderLayout.createSequentialGroup()
                .addComponent(lblImgLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(pnlLoader, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        this.dangNhap();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusGained
        // TODO add your handling code here:
        txtUser.setText("");
        lblErrorUser.setText("");
        lblErrorImguser.setVisible(false);
    }//GEN-LAST:event_txtUserFocusGained

    private void txtPwdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPwdFocusGained
        // TODO add your handling code here:
        txtPwd.setText("");
        lblErrorPwd.setText("");
        lblErrorImgpwd.setVisible(false);
    }//GEN-LAST:event_txtPwdFocusGained

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DangNhap_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DangNhap_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DangNhap_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DangNhap_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DangNhap_Dialog dialog = new DangNhap_Dialog(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblErrorImgpwd;
    private javax.swing.JLabel lblErrorImguser;
    private javax.swing.JLabel lblErrorPwd;
    private javax.swing.JLabel lblErrorUser;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblImgLoad;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblText;
    private javax.swing.JLabel lblText1;
    private javax.swing.JLabel lblText3;
    private javax.swing.JPanel pnlImage;
    private javax.swing.JPanel pnlLoader;
    private javax.swing.JPanel pnlLog;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JSeparator spr1;
    private javax.swing.JSeparator spr2;
    private javax.swing.JPasswordField txtPwd;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
    TaiKhoanDAO dao = new TaiKhoanDAO();

    private void init() {
        this.setLocationRelativeTo(null);
        lblErrorImguser.setVisible(false);
        lblErrorImgpwd.setVisible(false);
    }

    void dangNhap() {
        String manv = txtUser.getText();
        String matkhau = new String(txtPwd.getPassword());
        TaiKhoan taiKhoan = dao.selectById(manv);
        if (taiKhoan == null) {
            lblErrorUser.setText("Sai User !");
            lblErrorImguser.setVisible(true);
        } else if (!matkhau.equals(taiKhoan.getMatKhau())) {
            lblErrorPwd.setText("Sai Password !");
            lblErrorImgpwd.setVisible(true);
        } else {
            Auth.user = taiKhoan;
            loading();
        }
    }

    void loading() {
        Thread T = new Thread() {
            @Override
            public void run() {
                try {
                    for (int i = 0; i <= 4; i++) {
                        Thread.sleep(1000);
                        pnlLog.hide();
                        pnlLoader.show();
                        if (i == 4) {
                            DangNhap_Dialog.this.dispose();
                        }
                    }
                } catch (Exception e) {
                }
            }
        };
        T.start();
    }
}
